---
- name: "Install openssh-server"
  ansible.builtin.package:
    name:
      - openssh-server
    state: present
  become: true

- name: "Disable ssh root login"
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
  notify: "Restart sshd"
  become: true

- name: "Disable ssh empty password"
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^#?PermitEmptyPasswords"
    line: "PermitEmptyPasswords no"
  notify: "Restart sshd"
  become: true

- name: "Disable ssh password authentication"
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: "Restart sshd"
  become: true

- name: "Configure ssh to disconnect unresponsive ssh client after 10 minutes"
  block:
    - name: "Set ClientAliveInterval"
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "^#?ClientAliveInterval"
        line: "ClientAliveInterval 300"  # 5 min
      notify: "Restart sshd"
      become: true

    - name: "Set ClientAliveCountMax"
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "^#?ClientAliveCountMax"
        line: "ClientAliveCountMax 0"
      notify: "Restart sshd"
      become: true

- name: "Disable ssh tcp forwarding"
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^#?AllowTcpForwarding"
    line: "AllowTcpForwarding no"
  notify: "Restart sshd"
  become: true

- name: "Disable ssh tunneling"
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^#?PermitTunnel"
    line: "PermitTunnel no"
  notify: "Restart sshd"
  become: true

- name: "Disable ssh gateway ports"
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^#?GatewayPorts"
    line: "GatewayPorts no"
  notify: "Restart sshd"
  become: true

- name: "Disable ssh x11 forwarding"
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^#?X11Forwarding"
    line: "X11Forwarding no"
  notify: "Restart sshd"
  become: true
